services:
  alert-service:
    build:
      context: .
      dockerfile: alert-service/Dockerfile
    ports:
      - "8090:8090"

  sensor-movement-service:
    build:
      context: .
      dockerfile: sensor-movement-service/Dockerfile
    environment:
      ALERT_SERVICE_URL: http://alert-service:8090
    ports:
      - "8081:8081"
    depends_on:
      - alert-service

  sensor-temperature-service:
    build:
      context: .
      dockerfile: sensor-temperature-service/Dockerfile
    environment:
      ALERT_SERVICE_URL: http://alert-service:8090
    ports:
      - "8082:8082"
    depends_on:
      - alert-service

  sensor-access-service:
    build:
      context: .
      dockerfile: sensor-access-service/Dockerfile
    environment:
      ALERT_SERVICE_URL: http://alert-service:8090
    ports:
      - "8083:8083"
    depends_on:
      - alert-service

  gateway-service:
    build:
      context: .
      dockerfile: gateway-service/Dockerfile
    environment:
      MOVEMENT_SERVICE_URL: http://sensor-movement-service:8081
      TEMPERATURE_SERVICE_URL: http://sensor-temperature-service:8082
      ACCESS_SERVICE_URL: http://sensor-access-service:8083
      ALERT_SERVICE_URL: http://alert-service:8090
    ports:
      - "8080:8080"
    depends_on:
      - sensor-movement-service
      - sensor-temperature-service
      - sensor-access-service
      - alert-service

